### ISSUE TITLE
NameError import modules

### ISSUE THREAD

**Issue by AndreiBer** [DCC-Lab/PyTissueOptics#106]
**Describe the bug**
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[28], line 2
      1 from pytissueoptics import *
----> 2 print(ScatteringMaterial)

NameError: name 'ScatteringMaterial' is not defined

**Expected behavior**
Expected that module is imported

**Desktop (please complete the following information):**
Python 3.8.3
Visual Studio Code 1.81.1

**Comment by JLBegin** [comment]
It seems you are using the previous release of the package (version 1.0.4).
I recommend going through the new [installation instructions ](https://github.com/DCC-Lab/PyTissueOptics#installation)to get latest development state (2.0.0b1), not the pip release.

**Comment by AndreiBer** [comment]
thanks! that was the issue.
