### ISSUE TITLE
Photons are being logged outside of 3dModel (but in vaccum)

### ISSUE THREAD

**Issue by PyMarc2** [DCC-Lab/PyTissueOptics#67]
If you run the example `ex04.py` with enough photons, You will see some photons being logged outside the model. This suggests there is a bug either
- on the model polygons
- on the intersection precision
- on logging

The source has still to be found.
![image](https://user-images.githubusercontent.com/31829033/167261740-97b88dc4-e5d4-48be-b1b8-d3b372837479.png)
![image](https://user-images.githubusercontent.com/31829033/167261751-6d6bc1a0-bea7-405b-b3c1-52605da9212a.png)

**Comment by JLBegin** [comment]
Use following seed with the default number of photons (N=1000). 
```python
import numpy as np
np.random.seed(10)
```
![image](https://user-images.githubusercontent.com/29587649/167654200-06bca56f-98a4-419b-8b31-2e28f2e3b069.png)

**Comment by PyMarc2** [comment]
partially fixed, there are a lot less, but this is still present.

**Comment by JLBegin** [comment]
The others are coming from a few holes in the model, mainly at the forearms. 
![image](https://user-images.githubusercontent.com/29587649/167699275-7d22ff00-8dbe-451a-9da8-65460301cc6d.png)

**Comment by PyMarc2** [comment]
Fixed when using a fully closed model. The 3D model will be changed.
