### ISSUE TITLE
Read the Docs page does not exist

### ISSUE THREAD

**Issue by Romutulus** [DCC-Lab/PyTissueOptics#89]
**Describe the bug**
As the title. It is currently 404 Not Found.

**To Reproduce**
1. Click on the link on github.

**Expected behavior**
A documentation page

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux

**Additional context**

**Comment by JLBegin** [comment]
Sorry for the inconvenience, but the documentation has not yet been generated. I removed the link from the Readme file for the time being and merged the development branch which includes many new features, a more detailed [Readme](https://github.com/DCC-Lab/PyTissueOptics) file, and [examples](https://github.com/DCC-Lab/PyTissueOptics/tree/main/examples) which should help to get you started with the package.
